/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
#ifndef __RAML2AGL_SERVICE_CLASS_SERVICEROVERGY521_H_
#define __RAML2AGL_SERVICE_CLASS_SERVICEROVERGY521_H_

#pragma once
#include <cstddef>
#include <string.h>
#include <string>

extern "C"
{
    #define AFB_BINDING_VERSION 2
    #include <afb/afb-binding.h>
};

enum rover_button_id {
  user_button,
  shutdown_button,
  custom_button
};
enum rover_sensor_id {
  rear_right,
  rear_left,
  front_right,
  front_left,
  front,
  rear
};

class ServiceRoverGy521 {
public:
  ServiceRoverGy521();

  int init();

    /** Autogenrated doc for read_acc_x */
    int read_acc_x(int &out_acc_x);

    /** Autogenrated doc for read_acc_y */
    int read_acc_y(int &out_acc_y);

    /** Autogenrated doc for read_acc_z */
    int read_acc_z(int &out_acc_z);

    /** Autogenrated doc for read_angle_x */
    int read_angle_x(double &out_angle_x);

    /** Autogenrated doc for read_angle_y */
    int read_angle_y(double &out_angle_y);

    /** Autogenrated doc for read_angle_z */
    int read_angle_z(double &out_angle_z);

    /** Autogenrated doc for read_gyro_x */
    int read_gyro_x(int &out_gyro_x);

    /** Autogenrated doc for read_gyro_y */
    int read_gyro_y(int &out_gyro_y);

    /** Autogenrated doc for read_gyro_z */
    int read_gyro_z(int &out_gyro_z);

};

#endif //__RAML2AGL_SERVICE_CLASS_SERVICEROVERGY521_H_