/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
#ifndef __RAML2AGL_SERVICE_CLASS_SERVICEROVERUTILS_H_
#define __RAML2AGL_SERVICE_CLASS_SERVICEROVERUTILS_H_

#pragma once
#include <cstddef>
#include <string.h>
#include <string>

extern "C"
{
    #define AFB_BINDING_VERSION 2
    #include <afb/afb-binding.h>
};

enum rover_button_id {

};
enum rover_sensor_id {

};

class ServiceRoverUtils {
public:
  ServiceRoverUtils();

  int init();

    /** Autogenrated doc for get_bluetooth_status */
    int get_bluetooth_status(bool &out_is_on);

    /** Autogenrated doc for get_core_utilization */
    int get_core_utilization(double out_core_utilization[], int &out_core_utilization_size);

    /** Autogenrated doc for get_ethernet_status */
    int get_ethernet_status(bool &out_is_on);

    /** Autogenrated doc for get_honocloud_status */
    int get_honocloud_status(const char * in_device_id,
        const char * in_host_name,
        const char * in_password,
        const int in_port,
        const char * in_tenant_name,
        const char * in_user,
        bool &out_is_on);

    /** Autogenrated doc for get_internet_status */
    int get_internet_status(bool &out_is_on);

    /** Autogenrated doc for get_number_cores */
    int get_number_cores(int &out_num_cores);

    /** Autogenrated doc for get_wlan_status */
    int get_wlan_status(bool &out_is_on);

};

#endif //__RAML2AGL_SERVICE_CLASS_SERVICEROVERUTILS_H_