/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
#ifndef __RAML2AGL_SERVICE_CLASS_SERVICEROVERBUZZER_H_
#define __RAML2AGL_SERVICE_CLASS_SERVICEROVERBUZZER_H_

#pragma once
#include <cstddef>
#include <string.h>
#include <string>

extern "C"
{
    #define AFB_BINDING_VERSION 2
    #include <afb/afb-binding.h>
};

enum rover_button_id {
  user_button,
  shutdown_button,
  custom_button
};
enum rover_sensor_id {
  rear_right,
  rear_left,
  front_right,
  front_left,
  front,
  rear
};

class ServiceRoverBuzzer {
public:
  ServiceRoverBuzzer();

  int init();

    /** Autogenrated doc for get_frequency */
    int get_frequency(int &out_buzzer_frequency);

    /** Autogenrated doc for play_melody */
    int play_melody(const int in_melody[], const int in_melody_size,
        const double in_tempo[], const int in_tempo_size);

    /** Autogenrated doc for set_frequency */
    int set_frequency(const int in_buzzer_frequency);

    /** Autogenrated doc for set_off */
    int set_off();

    /** Autogenrated doc for set_on */
    int set_on();

    /** Autogenrated doc for set_tone */
    int set_tone(const int in_buzzer_frequency);

};

#endif //__RAML2AGL_SERVICE_CLASS_SERVICEROVERBUZZER_H_