/* Copyright 2018 Pedro Cuadra - pjcuadra@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* WARNING: This file is automatically generated by raml2agl */
#include <service/ServiceRoverDemo.h>

ServiceRoverDemo::ServiceRoverDemo() {
  AFB_NOTICE("[ServiceRoverDemo] Constructor ");
}

int ServiceRoverDemo::init() {
  AFB_NOTICE("[ServiceRoverDemo] Init ");
  return -1;
}


/** Autogenrated doc for run */
int ServiceRoverDemo::run(const rover_demo_id in_demo_id) {

  AFB_NOTICE("[ServiceRoverDemo] Run");
  AFB_ERROR("Method Run not implemented");

  return -1;
}
