#%RAML 1.0
title: Rover Test
mediaType: application/json
version: v1
baseUri: localhost:8000/api?token=x
/goforward1:
  description: "Move Forward"
  get:
/gobackward2:
  description: "Move Backwards"
  get:
/turnright3:
  description: "Turn Right"
  get:
/turnleft4:
  description: "Turn Left"
  get:
/stop5:
  description: "Stop the Rover"
  get:
/setspeed6:
  description: "Set the motors' speed"
  post:
    body:
      application/json:
        properties:
          speed:
            type: integer
