#%RAML 1.0
title: Rover Infrared Sensor
mediaType: application/json
version: v1
baseUri: localhost:8000/api?token=x
types:
  rover_sensor_id:
    enum:
      - rear_right
      - rear_left
      - front_right
      - front_left
      - front
      - rear
  rover_button_id:
    enum:
      - user_button
      - shutdown_button
      - custom_button
/read:
  description: "Read Data From Sensor"
  post:
    body:
      properties:
        sensor_id:
          type: rover_sensor_id
  get:
    responses:
      200:
        body:
          properties:
            distance:
              type: number
