#%RAML 1.0
title: Rover driving
mediaType: application/json
version: v1
baseUri: localhost:8000/api?token=x
types:
  rover_sensor_id:
    enum:
      - rear_right
      - rear_left
      - front_right
      - front_left
      - front
      - rear
  rover_button_id:
    enum:
      - user_button
      - shutdown_button
      - custom_button
  rover_demo_id:
    enum:
      - buzzer
      - driving
      - buttons
      - infrared
      - rover_demo_max
/goforward:
  description: "Move Forward"
  get:
/gobackward:
  description: "Move Backwards"
  get:
/turnright:
  description: "Turn Right"
  get:
/turnleft:
  description: "Turn Left"
  get:
/stop:
  description: "Stop the Rover"
  get:
/setspeed:
  description: "Set the motors' speed"
  post:
    body:
      application/json:
        properties:
          speed:
            type: integer
